{{- with index .Values "cluster-configs" "secrets" "argocd-repo-server" }}
{{- if index . "azure-client-secret" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "argocd-repo-server" "name" }}
  namespace: {{ index $.Values "cluster-configs" "secrets" "argocd-repo-server" "namespace" }}
type: Opaque
data:
  client-secret: {{ index $.Values "cluster-configs" "secrets" "argocd-repo-server" "azure-client-secret" | b64enc | quote }}
---
{{- end }}
{{- end }}
